version: '3'

volumes:
  db-data:
    driver: local

services:
  backend:
    build:
      context: .
    container_name: backend-prs
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '8080:8080'
  db:
    image: postgres:16-alpine
    container_name: postgres-prs
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data
