spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parking_db?currentSchema=parking
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver


  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true

security:
  jwt:
    secret: YXNrc3VoY3Zid2V1a2J3aWt1ZXZic2RrdWh2Z3lpZWthdXNnaHZxdWdpdmtpdWFzdmt1aHN2Ym9ld2hiZHM=
    access: 3600000
    refresh: 2592000000

springdoc:
  override-with-generic-response: false
